version: '3'
services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./home/sedki/Documents/nxtya:/home/sedki/Documents/nxtya
    #environment:
    

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  redis:
    image: redis:6.2.1
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  mysql:
  redis:


