export const GET_AUTH_REQUEST = "GET_AUTH_REQUEST ";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS ";
export const GET_AUTH_FAILURE = "GET_AUTH_FAILURE ";

export const FB_LOGIN_REQUEST = "FB_LOGIN_REQUEST ";
export const FB_LOGIN_SUCCESS = "FB_LOGIN_SUCCESS ";
export const FB_LOGIN_FAILURE = "FB_LOGIN_FAILURE ";

export const CONNECT_REQUEST = "CONNECT_REQUEST ";
export const CONNECT_SUCCESS = "CONNECT_SUCCESS ";
export const CONNECT_FAILURE = "CONNECT_FAILURE ";

export const SET_ZONE = "SET_ZONE ";
